### ISSUE TITLE
AYUDA

### ISSUE THREAD

**Issue by fernandomonterroso** [burbuja/opencart-spanish#2]
Muy buen aporte, solo consulto si esto solo es para la infaz de admistración, esque en tienda es decir vistas de cliente aun aparece en ingles si fueran tan amables de confirmarme.

**Comment by rsepulvedacl** [comment]
Debería verse en español, tanto en la administración como en la vista de cliente. De no ser así, se pueden borrar las cookies y elegir el idioma desde el menú que aparece en la parte superior de la tienda.
Como esto no se trata de un error de programación, sugiero hacerme llegar este tipo de preguntas a través del [formulario de contacto](https://www.burbuja.cl/contacto/).
Saludos.

**Comment by rsepulvedacl** [comment]
Debería verse en español, tanto en la administración como en la vista de cliente. De no ser así, se pueden borrar las cookies y elegir el idioma desde el menú que aparece en la parte superior de la tienda.
Como esto no se trata de un error de programación, sugiero hacerme llegar este tipo de preguntas a través del [formulario de contacto](https://www.burbuja.cl/contacto/).
Saludos.
